name: Build nightly
on:
  push:
    branches:
      - master
    tags: ["v*"]
    paths:
      - Jellyfin.Plugin.PhoenixAdult/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Set nightly version
        run: |
          echo "VERSION=$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Jellyfin Plugin for release
        run: |
          dotnet build -c Release /p:Version=${{ env.VERSION }}

      - name: Build Emby Plugin for release
        run: |
          dotnet build -c Release.Emby /p:Version=${{ env.VERSION }}

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "obj|.git"
          path: .
          depth: 8

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            **/Jellyfin.Plugin.PhoenixAdult@v${{ env.VERSION }}.zip
            **/Emby.Plugin.PhoenixAdult@v${{ env.VERSION }}.zip
